#### About
###### 1
###### 2
###### 3

##### Loading Data
###### The first step is to loading data.

In [ ]:
%pip install kagglehub

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import kagglehub
import os
from IPython.display import display

# easy read 
pd.set_option('display.float_format', lambda x: '%.2f' % x)
# Download latest version
path = kagglehub.dataset_download("artermiloff/steam-games-dataset")
file_path = os.path.join(path, "games_march2025_full.csv")

In [8]:
dataset = pd.read_csv(file_path)

display(dataset)

display(dataset.info())

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",86,8632939,82,96473
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle ...",59,2513842,68,16720
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
3,271590,Grand Theft Auto V Legacy,2015-04-13,17,0.00,0,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multip...",87,1803832,92,17517
4,488824,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,19.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,0,0,0,0,0,"{'FPS': 8082, 'Multiplayer': 6139, 'Tactical':...",84,1168404,76,13017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94943,2115110,Outrun Them,2024-02-29,0,3.99,0,The name of the game is literally the game. Ou...,The name of the game is literally the game. Ou...,It's all in the name.. outrun them.,NaN,...,0,0,0,0,0,"{'2D Platformer': 91, 'Runner': 85, 'Platforme...",-1,-1,-1,-1
94944,1174200,Lands of Pharaoh: Episode 1,2020-01-07,0,10.00,0,Join Our Discord Channel About the Game Briefl...,Briefly: Lands of Pharaoh is a third person vi...,Lands of Pharaoh is a multi-camera-angle based...,NaN,...,0,0,0,0,0,"{'Action': 43, 'Adventure': 41, 'Indie': 41, '...",-1,-1,-1,-1
94945,1160190,Player One,2019-10-10,0,1.99,0,Player One is a new 3D game where you take con...,Player One is a new 3D game where you take con...,"3D Game, Thirdperson Platformer",NaN,...,0,0,0,0,0,"{'Indie': 31, 'Early Access': 21}",-1,-1,-1,-1
94946,3380340,DragonRoad,2025-01-25,0,29.99,0,"This is an open world game on 3D, also a m...","This is an open world game on 3D, also a m...","This is an open world game on 3D, Also a missi...",NaN,...,0,0,0,0,0,"{'RPG': 117, 'Action-Adventure': 111, 'Strateg...",-1,-1,-1,-1
94947,763730,Ragtag Adventurers,2018-03-01,0,9.99,0,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a boss rush game that pi...,NaN,...,0,0,0,0,0,"{'Action': 22, 'Indie': 21}",-1,-1,-1,-1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94948 entries, 0 to 94947
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   appid                     94948 non-null  int64
 1   name                      94946 non-null  object
 2   release_date              94948 non-null  object
 3   required_age              94948 non-null  int64
 4   price                     94948 non-null  float64
 5   dlc_count                 94948 non-null  int64
 6   detailed_description      89522 non-null  object
 7   about_the_game            89499 non-null  object
 8   short_description         89599 non-null  object
 9   reviews                   10428 non-null  object
 10  header_image              94948 non-null  object
 11  website                   41194 non-null  object
 12  support_url               44185 non-null  object
 13  support_email             78848 non-null  object
 14  windows                   94948 non-null  bool
 15  mac                       94948 non-null  bool
 16  linux                     94948 non-null  bool
 17  metacritic_score          94948 non-null  int64
 18  metacritic_url            3576 non-null   object
 19  achievements              94948 non-null  int64
 20  recommendations           94948 non-null  int64
 21  notes                     16652 non-null  object
 22  supported_languages       94948 non-null  object
 23  full_audio_languages      94948 non-null  object
 24  packages                  94948 non-null  object
 25  developers                94948 non-null  object
 26  publishers                94948 non-null  object
 27  categories                94948 non-null  object
 28  genres                    94948 non-null  object
 29  screenshots               94948 non-null  object
 30  movies                    94948 non-null  object
 31  user_score                94948 non-null  int64
 32  score_rank                39 non-null     float64
 33  positive                  94948 non-null  int64
 34  negative                  94948 non-null  int64
 35  estimated_owners          94948 non-null  object
 36  average_playtime_forever  94948 non-null  int64
 37  average_playtime_2weeks   94948 non-null  int64
 38  median_playtime_forever   94948 non-null  int64
 39  median_playtime_2weeks    94948 non-null  int64
 40  discount                  94948 non-null  int64
 41  peak_ccu                  94948 non-null  int64
 42  tags                      94948 non-null  object
 43  pct_pos_total             94948 non-null  int64
 44  num_reviews_total         94948 non-null  int64
 45  pct_pos_recent            94948 non-null  int64
 46  num_reviews_recent        94948 non-null  int64
dtypes: bool(3), float64(2), int64(19), object(23)
memory usage: 32.1+ MB

None

##### Data Description

In [10]:
dataset.describe()

,appid,required_age,price,dlc_count,metacritic_score,achievements,recommendations,user_score,score_rank,positive,...,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
count,94948.00,94948.00,94948.00,94948.00,94948.00,94948.00,94948.00,94948.00,39.00,94948.00,...,94948.00,94948.00,94948.00,94948.00,94948.00,94948.00,94948.00,94948.00,94948.00,94948.00
mean,1707530.53,0.18,6.91,0.56,2.76,19.54,1022.21,0.03,99.13,1217.90,...,108.61,4.76,108.37,5.02,4.31,92.85,44.63,1448.04,5.33,16.88
std,926434.62,1.70,13.07,14.92,14.11,159.80,22741.51,1.57,0.70,30979.74,...,6620.83,175.96,8555.99,184.24,16.11,5554.79,40.84,35481.41,22.46,459.11
min,20.00,-1.00,0.00,0.00,0.00,0.00,0.00,0.00,98.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,-1.00,-1.00,-1.00,-1.00
25%,887337.50,0.00,0.99,0.00,0.00,0.00,0.00,0.00,99.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,-1.00,-1.00,-1.00,-1.00
50%,1591145.00,0.00,3.99,0.00,0.00,2.00,0.00,0.00,99.00,8.00,...,0.00,0.00,0.00,0.00,0.00,0.00,58.00,15.00,-1.00,-1.00
75%,2491702.50,0.00,9.99,0.00,0.00,19.00,0.00,0.00,100.00,51.00,...,0.00,0.00,0.00,0.00,0.00,0.00,84.00,80.00,-1.00,-1.00
max,3570420.00,21.00,999.98,3427.00,97.00,9821.00,4401572.00,100.00,100.00,7480813.00,...,1462997.00,18568.00,1462997.00,18568.00,100.00,1212356.00,100.00,8632939.00,100.00,96473.00